#!/usr/bin/env python3
"""Agent signing key (ADR-11 A3): derive the JWK of ``secrets/ucp-agent-signing-key.pem``
exactly like ``shopware_common.http_signing.public_jwk`` and publish it as the **single**
``signing_keys`` entry of ``agent-profile.json``.

    python docker/agent_key.py write-profile --pem secrets/ucp-agent-signing-key.pem --profile agent-profile.json
    python docker/agent_key.py check         --pem ... --profile ...   # exit 1 unless profile == [jwk]
    python docker/agent_key.py jwk           --pem ...                 # print the JWK
    python docker/agent_key.py kid           --pem ...                 # print the key id

Needs the repo venv (``cryptography``); run with ``.venv/bin/python``. The PEM itself is
generated by bootstrap with ``openssl`` only when missing, so re-runs keep the same key and
therefore the same ``kid`` (base64url(sha256(uncompressed point))[:32]).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from shopware_common.http_signing import RequestSigner  # noqa: E402


def load_signer(pem_path: Path) -> RequestSigner:
    if not pem_path.exists():
        raise FileNotFoundError(f"{pem_path} missing — bootstrap generates it with openssl")
    return RequestSigner.from_pem_file(pem_path)


def write_profile(profile_path: Path, jwk: dict[str, str]) -> bool:
    """Replace ``signing_keys`` with ``[jwk]``. Returns True when the file changed."""
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    if profile.get("signing_keys") == [jwk]:
        return False
    profile["signing_keys"] = [jwk]
    profile_path.write_text(json.dumps(profile, indent=2) + "\n", encoding="utf-8")
    return True


def check_profile(profile_path: Path, jwk: dict[str, str]) -> list[str]:
    problems: list[str] = []
    profile = json.loads(profile_path.read_text(encoding="utf-8"))
    keys = profile.get("signing_keys")
    if not isinstance(keys, list) or len(keys) != 1:
        problems.append(f"signing_keys must have exactly one entry, has {keys!r}")
    elif keys[0] != jwk:
        problems.append("signing_keys[0] does not match the PEM's public key")
    return problems


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("command", choices=["write-profile", "check", "jwk", "kid"])
    parser.add_argument("--pem", required=True, type=Path)
    parser.add_argument("--profile", type=Path, default=REPO_ROOT / "agent-profile.json")
    args = parser.parse_args()

    signer = load_signer(args.pem)
    jwk = signer.jwk()

    if args.command == "jwk":
        print(json.dumps(jwk, indent=2))
        return 0
    if args.command == "kid":
        print(signer.kid)
        return 0
    if args.command == "write-profile":
        changed = write_profile(args.profile, jwk)
        print(
            f"agent-profile.json signing_keys = [{signer.kid}] ({'updated' if changed else 'unchanged'})"
        )
        return 0
    problems = check_profile(args.profile, jwk)
    for problem in problems:
        print(f"agent_key check: {problem}", file=sys.stderr)
    if not problems:
        print(f"agent-profile.json publishes exactly one signing key: {signer.kid}")
    return 1 if problems else 0


if __name__ == "__main__":
    raise SystemExit(main())
